version: 1.0.{build}
skip_tags: false
shallow_clone: true
install:
    - ps: Install-Product node 4.2.3
    #- ps: Start-FileDownload 'https://s3.amazonaws.com/mozilla-games/emscripten/releases/emsdk-1.34.1-full-64bit.exe'
    #- emsdk-1.34.1-full-64bit.exe /S /D=C:\emscripten
build:
    verbosity: minimal
build_script:
    - scripts\appveyor.bat
