language: cpp

sudo: false

addons:
    apt:
        packages:
            - binutils-mingw-w64-i686
            - gcc-mingw-w64-i686
            - g++-mingw-w64-i686
            - gcc-multilib
            - lib32stdc++6-4.7-dev
            - lib32stdc++6

os:
    - linux
    - osx

branches:
    only:
        - /^v[0-9].*$/
        - master

script: scripts/travis.sh
