language: cpp

os:
    - osx
    - linux

before_install:
    - if [ "$TRAVIS_OS_NAME" = "linux" ] then sudo apt-get update -qq
    - if [ "$TRAVIS_OS_NAME" = "linux" ] then sudo pt-get install -y libc6-dev-i386 g++-multilib
    - if [ "$TRAVIS_OS_NAME" = "linux" ] then sudo pt-get install -y libasound2-dev
    - if [ "$TRAVIS_OS_NAME" = "linux" ] then sudo pt-get install -y libasound2-dev:i386
    - if [ "$TRAVIS_OS_NAME" = "linux" ] then sudo pt-get install -y mingw-w64
    - if [ "$TRAVIS_OS_NAME" = "linux" ] then sudo pt-get install -y python2.7 nodejs default-jre

script: ./travis/build.sh
