language: cpp

matrix:
    include:
        - os: osx
          env:
            - TARGET=osx.release
            - MK_TARGET=test
        - os: osx
          env:
            - TARGET=ios.release
            - MK_TARGET=default
        - os: linux
          env:
            - TARGET=linux64.release
            - MK_TARGET=test
        
script: make $MK_TARGET
