language: cpp

os:
    - linux
    - osx

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y binutils-mingw-w64-i686
    - sudo apt-get install -y gcc-mingw-w64-i686
    - sudo apt-get install -y g++-mingw-w64-i686
        
script: scripts/travis.sh
