language: cpp

os:
    - osx
    - linux

before_install:
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update -qq; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo pt-get install -y libc6-dev-i386 g++-multilib; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo pt-get install -y libasound2-dev; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo pt-get install -y libasound2-dev:i386; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo pt-get install -y mingw-w64; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo pt-get install -y python2.7 nodejs default-jre; fi

script: ./travis/build.sh
